openapi: 3.1.0
info:
  title: SkyHealth Middleware API
  version: "0.2.0"
  description: GA4 + Social KPI endpoints for SkyHealth Media agent.

servers:
  - url: https://skyhealth-media-ga4.onrender.com

paths:
  /kpi/social:
    get:
      operationId: getSocialKpis
      summary: Get social KPIs (Instagram/Facebook)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: platform
          description: Platform ("instagram" or "facebook")
          required: true
          schema: { type: string }
        - in: query
          name: accountId
          description: Instagram User ID or Facebook Page ID
          required: true
          schema: { type: string }
        - in: query
          name: postLimit
          description: Number of posts to fetch (default 5)
          schema: { type: integer }
      responses:
        "200":
          description: Social KPI payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialKpiResponse'
        "401":
          description: Missing or invalid bearer token
        "500":
          description: Social KPI fetch failed

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    SocialKpiResponse:
      type: object
      description: May include either instagram or facebook object.
      properties:
        instagram:
          type: object
          nullable: true
          properties:
            username: { type: string, nullable: true }
            followers: { type: integer, nullable: true }
            media_count: { type: integer, nullable: true }
            posts:
              type: array
              items:
                type: object
                properties:
                  id: { type: string }
                  caption: { type: string, nullable: true }
                  media_url: { type: string, nullable: true }
                  permalink: { type: string, nullable: true }
                  like_count: { type: integer, nullable: true }
                  comments_count: { type: integer, nullable: true }
                  timestamp: { type: string, format: date-time, nullable: true }
        facebook:
          type: object
          nullable: true
          properties:
            page_name: { type: string, nullable: true }
            followers: { type: integer, nullable: true }
            likes: { type: integer, nullable: true }
            posts:
              type: array
              items:
                type: object
                properties:
                  id: { type: string }
                  message: { type: string, nullable: true }
                  permalink_url: { type: string, nullable: true }
                  created_time: { type: string, format: date-time, nullable: true }
                  like_count: { type: integer, nullable: true }
                  comments_count: { type: integer, nullable: true }
      additionalProperties: true

