openapi: 3.1.0
info:
  title: SkyHealth Middleware API
  version: "0.1.0"
  description: GA4 + Social KPI endpoints for SkyHealth Media agent.

servers:
  - url: https://skyhealth-media-ga4.onrender.com

paths:
  /health:
    get:
      operationId: getHealth
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /kpi/ga4:
    get:
      operationId: getGa4Kpis
      summary: Get GA4 KPIs (sessions/users + top pages)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: property_id
          description: Numeric GA4 Property ID (optional if set on server)
          schema: { type: string }
        - in: query
          name: top_limit
          description: Max number of top pages
          schema: { type: integer, default: 10 }
      responses:
        "200":
          description: GA4 KPI payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ga4KpiResponse'
        "401":
          description: Missing or invalid bearer token

  /kpi/social:
    get:
      operationId: getSocialKpis
      summary: Get social KPIs (Instagram/YouTube/TikTok/Facebook when configured)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: platform
          description: Social platform to query (instagram | facebook | youtube | tiktok)
          required: true
          schema:
            type: string
            enum: [instagram, facebook, youtube, tiktok]
        - in: query
          name: handles
          description: Comma-separated handles or IDs, e.g. "1784...,UCxxxx,biz_123"
          schema:
            type: string
      responses:
        "200":
          description: Social KPI payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialKpiResponse'
        "401":
          description: Missing or invalid bearer token

  /prospects:
    get:
      operationId: listProspects
      summary: Get sample prospects (demo data)
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: market
          schema: { type: string }
        - in: query
          name: service
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, default: 25 }
      responses:
        "200":
          description: Prospects list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prospect'
        "401":
          description: Missing or invalid bearer token

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    HealthResponse:
      type: object
      properties:
        ok:
          type: boolean

    Ga4KpiResponse:
      type: object
      properties:
        sessions:
          type: object
          properties:
            7d: { type: integer }
            28d: { type: integer }
        users:
          type: object
          properties:
            7d: { type: integer }
            28d: { type: integer }
        top_pages:
          type: array
          items:
            type: object
            properties:
              path: { type: string }
              pv: { type: integer }
              sessions: { type: integer }
        events:
          type: array
          items: { type: object }
        conversions:
          type: array
          items: { type: object }

    SocialKpiResponse:
      type: object
      description: May include any of the listed platform objects if configured.
      properties:
        instagram:
          type: object
          nullable: true
          properties:
            username: { type: string, nullable: true }
            followers: { type: integer, nullable: true }
            media_count: { type: integer, nullable: true }
        facebook:
          type: object
          nullable: true
          properties:
            page_name: { type: string, nullable: true }
            followers: { type: integer, nullable: true }
            likes: { type: integer, nullable: true }
        youtube:
          type: object
          nullable: true
          properties:
            title: { type: string, nullable: true }
            subs: { type: integer, nullable: true }
            views: { type: integer, nullable: true }
            videos: { type: integer, nullable: true }
        tiktok:
          type: object
          nullable: true
          properties:
            note: { type: string, nullable: true }
      additionalProperties: true

    Prospect:
      type: object
      properties:
        name: { type: string }
        website: { type: string, nullable: true }
        instagram: { type: string, nullable: true }
        last_post_days: { type: integer, nullable: true }
        notes: { type: string }
